import type { BlackjackSeatId } from '../../../src/schemas/casinoSchemas/BlackjackSeatId';
import type { ConnectionId } from '../../../src/schemas/casinoSchemas/ConnectionId';
import type { HexColour } from '../../../src/schemas/casinoSchemas/HexColour';
import type { IsoTimestamp } from '../../../src/schemas/casinoSchemas/IsoTimestamp';
import type { ProfileId } from '../../../src/schemas/casinoSchemas/ProfileId';
import type { ProfileToken } from '../../../src/schemas/casinoSchemas/ProfileToken';
import type { ProfileTokenHash } from '../../../src/schemas/casinoSchemas/ProfileTokenHash';
import { profileIdSchema } from '../../../src/schemas/casinoSchemas/profileIdSchema';
import type { RoomId } from '../../../src/schemas/casinoSchemas/RoomId';
import type { RoomSeatId } from '../../../src/multiplayer/protocol/RoomSeatId';
import type { ServerInstanceId } from '../../../src/schemas/casinoSchemas/ServerInstanceId';
import type { SessionId } from '../../../src/schemas/casinoSchemas/SessionId';
import type { SettlementId } from '../../../src/schemas/casinoSchemas/SettlementId';
import type { TransactionId } from '../../../src/schemas/casinoSchemas/TransactionId';
import { blackjackSeatIdSchema } from '../../../src/schemas/casinoSchemas/blackjackSeatIdSchema';
import { connectionIdSchema } from '../../../src/schemas/casinoSchemas/connectionIdSchema';
import { hexColourSchema } from '../../../src/schemas/casinoSchemas/hexColourSchema';
import { isoTimestampSchema } from '../../../src/schemas/casinoSchemas/isoTimestampSchema';
import { profileTokenSchema } from '../../../src/schemas/casinoSchemas/profileTokenSchema';
import { profileTokenHashSchema } from '../../../src/schemas/casinoSchemas/profileTokenHashSchema';
import { roomIdSchema } from '../../../src/schemas/casinoSchemas/roomIdSchema';
import { roomSeatIdSchema } from '../../../src/schemas/casinoSchemas/roomSeatIdSchema';
import { serverInstanceIdSchema } from '../../../src/schemas/casinoSchemas/serverInstanceIdSchema';
import { sessionIdSchema } from '../../../src/schemas/casinoSchemas/sessionIdSchema';
import { settlementIdSchema } from '../../../src/schemas/casinoSchemas/settlementIdSchema';
import { transactionIdSchema } from '../../../src/schemas/casinoSchemas/transactionIdSchema';

export const testBlackjackSeatId = (value: string): BlackjackSeatId => blackjackSeatIdSchema.parse(value);
export const testConnectionId = (value: string): ConnectionId => connectionIdSchema.parse(value);
export const testHexColour = (value: string): HexColour => hexColourSchema.parse(value);
export const testIsoTimestamp = (value: string): IsoTimestamp => isoTimestampSchema.parse(value);
export const testProfileId = (value: string): ProfileId => profileIdSchema.parse(value);
export const testProfileToken = (value: string): ProfileToken => profileTokenSchema.parse(value);
export const testProfileTokenHash = (value: string): ProfileTokenHash => profileTokenHashSchema.parse(value);

export const testRoomId = (value: string): RoomId => roomIdSchema.parse(value);
export const testRoomSeatId = (value: string): RoomSeatId => roomSeatIdSchema.parse(value);
export const testServerInstanceId = (value: string): ServerInstanceId => serverInstanceIdSchema.parse(value);
export const testSessionId = (value: string): SessionId => sessionIdSchema.parse(value);
export const testSettlementId = (value: string): SettlementId => settlementIdSchema.parse(value);
export const testTransactionId = (value: string): TransactionId => transactionIdSchema.parse(value);
