import type { CasinoGameId } from '../../game/ids';
import type { SlotSymbol } from '../../game/slots/SlotSymbol';
import type { CasinoAsset } from './CasinoAsset';
import { createCasinoAsset } from './createCasinoAsset';

export const casinoAssets = {
  lobbyBackground: createCasinoAsset('lobby.background', '/assets/lobby/warehouse-lobby.png', 'lobby', 'background', 'generated-final', 'imagegen', '1672x941'),
  beatTheHouseTable: createCasinoAsset(
    'beat-the-house.table',
    '/assets/beat-the-house/table.png',
    'beat-the-house',
    'table',
    'approved-user-provided',
    'user-provided',
    '1672x941',
  ),
  beatTheHouseChips: createCasinoAsset(
    'beat-the-house.chips',
    '/assets/common/chips-sheet.png',
    'beat-the-house',
    'chip-sheet',
    'approved-user-provided',
    'user-provided',
    '1536x1024',
    true,
  ),
  blackjackTable: createCasinoAsset('blackjack.table', '/assets/blackjack/table.png', 'blackjack', 'table', 'generated-final', 'imagegen', '1585x992'),
  gameTiles: {
    'beat-the-house': createCasinoAsset(
      'lobby.tile.beat-the-house',
      '/assets/lobby/game-tiles/beat-the-house.png',
      'lobby',
      'game-tile',
      'generated-final',
      'imagegen',
      '1672x941',
    ),
    blackjack: createCasinoAsset(
      'lobby.tile.blackjack',
      '/assets/lobby/game-tiles/blackjack.png',
      'lobby',
      'game-tile',
      'generated-final',
      'imagegen',
      '1672x941',
    ),
    'slots:thai-princess': createCasinoAsset(
      'lobby.tile.thai-princess',
      '/assets/lobby/game-tiles/thai-princess.png',
      'lobby',
      'game-tile',
      'generated-final',
      'imagegen',
      '1672x941',
    ),
  } satisfies Record<CasinoGameId, CasinoAsset>,
  slotFrames: {
    'thai-princess': createCasinoAsset(
      'slots.thai-princess.frame',
      '/assets/slots/thai-princess/frame.png',
      'slots',
      'slot-frame',
      'generated-final',
      'imagegen',
      '1448x1086',
    ),
  },
  slotSymbols: {
    princess: createCasinoAsset(
      'slots.symbol.princess',
      '/assets/slots/symbols/princess.png',
      'slots',
      'slot-symbol',
      'generated-final',
      'imagegen',
      '512x512',
      true,
    ),
    lotus: createCasinoAsset('slots.symbol.lotus', '/assets/slots/symbols/lotus.png', 'slots', 'slot-symbol', 'generated-final', 'imagegen', '512x512', true),
    elephant: createCasinoAsset(
      'slots.symbol.elephant',
      '/assets/slots/symbols/elephant.png',
      'slots',
      'slot-symbol',
      'generated-final',
      'imagegen',
      '512x512',
      true,
    ),
    temple: createCasinoAsset(
      'slots.symbol.temple',
      '/assets/slots/symbols/temple.png',
      'slots',
      'slot-symbol',
      'generated-final',
      'imagegen',
      '512x512',
      true,
    ),
    fan: createCasinoAsset('slots.symbol.fan', '/assets/slots/symbols/fan.png', 'slots', 'slot-symbol', 'generated-final', 'imagegen', '512x512', true),
    orchid: createCasinoAsset(
      'slots.symbol.orchid',
      '/assets/slots/symbols/orchid.png',
      'slots',
      'slot-symbol',
      'generated-final',
      'imagegen',
      '512x512',
      true,
    ),
  } satisfies Record<SlotSymbol, CasinoAsset>,
} as const;
