import type { AppElements } from './AppElements';

export const collectElements = (): AppElements => {
  const query = <ElementType extends Element>(selector: string): ElementType => {
    const element = document.querySelector<ElementType>(selector);
    if (!element) {
      throw new Error(`Missing required element: ${selector}`);
    }
    return element;
  };

  return {
    setup: query('#setup'),
    shell: query('#casinoShell'),
    connectionOverlay: query('#connectionOverlay'),
    profileNameInput: query('#profileNameInput'),
    createProfileButton: query('#createProfileBtn'),
    profileList: query('#profileList'),
    startSessionButton: query('#startSessionBtn'),
    saveStatus: query('#saveStatus'),
    muteToggle: query('#muteToggle'),
    masterVolume: query('#masterVolume'),
    musicVolume: query('#musicVolume'),
    effectsVolume: query('#effectsVolume'),
    dealingVolume: query('#dealingVolume'),
    chipsVolume: query('#chipsVolume'),
    slotsVolume: query('#slotsVolume'),
    winsVolume: query('#winsVolume'),
    bonusVolume: query('#bonusVolume'),
    uiVolume: query('#uiVolume'),
    ambienceVolume: query('#ambienceVolume'),
    gameTabs: [...document.querySelectorAll<HTMLButtonElement>('[data-game]')],
    playerStrip: query('#playerStrip'),
    gameLobby: query('#gameLobby'),
    houseAdvancePanel: query('#houseAdvancePanel'),
    houseAdvanceButton: query('#houseAdvanceBtn'),
    gameLobbyTiles: query('#gameLobbyTiles'),
    roomLobby: query('#roomLobby'),
    roomGameTitle: query('#roomGameTitle'),
    roomGameDescription: query('#roomGameDescription'),
    backToLobbyButton: query('#backToLobbyBtn'),
    switchProfileButton: query('#switchProfileBtn'),
    sessionLimitInput: query('#sessionLimitInput'),
    sessionNotice: query('#sessionNotice'),
    roomNameInput: query('#roomNameInput'),
    roomMaxPlayersInput: query('#roomMaxPlayersInput'),
    roomRefreshButton: query('#roomRefreshBtn'),
    hostRoomButton: query('#hostRoomBtn'),
    leaveRoomButton: query('#leaveRoomBtn'),
    roomStatus: query('#roomStatus'),
    roomMenu: query('#roomMenu'),
    roomSeats: query('#roomSeats'),
    roomBrowser: query('#roomBrowser'),
    tableHost: query('#tableHost'),
    beatSeatStatus: query('#beatSeatStatus'),
    blackjackView: query('#blackjackView'),
    slotsView: query('#slotsView'),
    gameHud: query('#gameHud'),
    hudOverflowMenu: query('#hudOverflowMenu'),
    moneyPill: query('#moneyPill'),
    actionDock: query('#actionDock'),
    bankroll: query('#bankroll'),
    bankrollDelta: query('#bankrollDelta'),
    houseAdvancePill: query('#houseAdvancePill'),
    profileStats: query('#profileStats'),
    auditLog: query('#auditLog'),
    onTable: query('#onTable'),
    log: query('#log'),
    chipRail: query('#chipRail'),
    chipButtons: [...document.querySelectorAll<HTMLButtonElement>('[data-chip]')],
    beatControls: query('#beatControls'),
    blackjackControls: query('#blackjackControls'),
    slotsControls: query('#slotsControls'),
    beatRules: query('#beatRules'),
    beatPaytable: query('#beatPaytable'),
    blackjackRules: query('#blackjackRules'),
    blackjackPaytable: query('#blackjackPaytable'),
    slotsRules: query('#slotsRules'),
    slotsPaytable: query('#slotsPaytable'),
    dealButton: query('#dealBtn'),
    nextButton: query('#nextBtn'),
    hitButton: query('#hitBtn'),
    stickButton: query('#stickBtn'),
    rebetButton: query('#rebetBtn'),
    clearButton: query('#clearBtn'),
    addMoneyButton: query('#addMoneyBtn'),
    subtractMoneyButton: query('#subtractMoneyBtn'),
    resetMoneyButton: query('#resetMoneyBtn'),
    resetAllButton: query('#resetAllBtn'),
    clearSavesButton: query('#clearSavesBtn'),
    layoutOverlayButton: query('#layoutOverlayBtn'),
    adminTokenInput: query('#adminTokenInput'),
    authorizeAdminButton: query('#authorizeAdminBtn'),
    moneyInput: query('#moneyInput'),
    blackjackWager: query('#blackjackWager'),
    blackjackDealButton: query('#blackjackDealBtn'),
    blackjackHitButton: query('#blackjackHitBtn'),
    blackjackStandButton: query('#blackjackStandBtn'),
    blackjackDoubleButton: query('#blackjackDoubleBtn'),
    blackjackSplitButton: query('#blackjackSplitBtn'),
    blackjackInsuranceButton: query('#blackjackInsuranceBtn'),
    blackjackNewButton: query('#blackjackNewBtn'),
    blackjackStatus: query('#blackjackStatus'),
    blackjackPlayerCards: query('#blackjackPlayerCards'),
    blackjackDealerCards: query('#blackjackDealerCards'),
    blackjackResult: query('#blackjackResult'),
    blackjackSeats: query('#blackjackSeats'),
    slotsTitle: query('#slotsTitle'),
    slotsWager: query('#slotsWager'),
    slotsWagerButton: query('#slotsWagerBtn'),
    slotsReadyButton: query('#slotsReadyBtn'),
    slotsSpinButton: query('#slotsSpinBtn'),
    bonusPickButtons: [...document.querySelectorAll<HTMLButtonElement>('[data-bonus-pick]')],
    slotsStatus: query('#slotsStatus'),
    slotReels: query('#slotReels'),
    slotsResult: query('#slotsResult'),
    slotsRoomPlayers: query('#slotsRoomPlayers'),
  };
};
