import { selectElement } from './selectElement';
import { selectElements } from './selectElements';
import type { AppElements } from './AppElements';

/**
 * Collects all required DOM elements from the document.
 *
 * @returns Typed references to every element required by the application.
 * @throws {Error} If a required element is missing from the document.
 */
export const collectElements = (): AppElements => ({
  muteToggle: selectElement<HTMLInputElement>('#muteToggle'),
  masterVolume: selectElement<HTMLInputElement>('#masterVolume'),
  musicVolume: selectElement<HTMLInputElement>('#musicVolume'),
  effectsVolume: selectElement<HTMLInputElement>('#effectsVolume'),
  dealingVolume: selectElement<HTMLInputElement>('#dealingVolume'),
  chipsVolume: selectElement<HTMLInputElement>('#chipsVolume'),
  slotsVolume: selectElement<HTMLInputElement>('#slotsVolume'),
  winsVolume: selectElement<HTMLInputElement>('#winsVolume'),
  bonusVolume: selectElement<HTMLInputElement>('#bonusVolume'),
  uiVolume: selectElement<HTMLInputElement>('#uiVolume'),
  ambienceVolume: selectElement<HTMLInputElement>('#ambienceVolume'),
  beatSettlementAnnouncement: selectElement('#beatSettlementAnnouncement'),
  beatSeatStatus: selectElement<HTMLDivElement>('#beatSeatStatus'),
  beatShoeStatus: selectElement<HTMLDivElement>('#beatShoeStatus'),
  beatShoeLabel: selectElement('#beatShoeLabel'),
  beatShoeCounts: selectElement('#beatShoeCounts'),
  beatShoeMeter: selectElement<HTMLMeterElement>('#beatShoeMeter'),
  beatShoeCut: selectElement('#beatShoeCut'),
  beatShoeCue: selectElement('#beatShoeCue'),
  beatTableStatus: selectElement('#beatTableStatus'),
  beatControls: selectElement<HTMLDivElement>('#beatControls'),
  beatRules: selectElement('#beatRules'),
  beatPaytable: selectElement('#beatPaytable'),
  beatHalfChipIndicator: selectElement('#beatHalfChipIndicator'),
  blackjackView: selectElement<HTMLDivElement>('#blackjackView'),
  blackjackControls: selectElement<HTMLDivElement>('#blackjackControls'),
  blackjackRules: selectElement('#blackjackRules'),
  blackjackPaytable: selectElement('#blackjackPaytable'),
  blackjackStatus: selectElement('#blackjackStatus'),
  blackjackPlayerCards: selectElement('#blackjackPlayerCards'),
  blackjackDealerCards: selectElement('#blackjackDealerCards'),
  blackjackResult: selectElement('#blackjackResult'),
  blackjackSeats: selectElement('#blackjackSeats'),
  blackjackWager: selectElement<HTMLInputElement>('#blackjackWager'),
  blackjackDealButton: selectElement<HTMLButtonElement>('#blackjackDealBtn'),
  blackjackHitButton: selectElement<HTMLButtonElement>('#blackjackHitBtn'),
  blackjackStandButton: selectElement<HTMLButtonElement>('#blackjackStandBtn'),
  blackjackDoubleButton: selectElement<HTMLButtonElement>('#blackjackDoubleBtn'),
  blackjackSplitButton: selectElement<HTMLButtonElement>('#blackjackSplitBtn'),
  blackjackInsuranceButton: selectElement<HTMLButtonElement>('#blackjackInsuranceBtn'),
  blackjackNewButton: selectElement<HTMLButtonElement>('#blackjackNewBtn'),
  slotsView: selectElement<HTMLDivElement>('#slotsView'),
  slotsTitle: selectElement('#slotsTitle'),
  slotsWager: selectElement<HTMLInputElement>('#slotsWager'),
  slotsWagerButton: selectElement<HTMLButtonElement>('#slotsWagerBtn'),
  slotsReadyButton: selectElement<HTMLButtonElement>('#slotsReadyBtn'),
  slotsSpinButton: selectElement<HTMLButtonElement>('#slotsSpinBtn'),
  bonusPickButtons: selectElements<HTMLButtonElement>('[data-bonus-pick]'),
  slotsControls: selectElement<HTMLDivElement>('#slotsControls'),
  slotsRules: selectElement('#slotsRules'),
  slotsPaytable: selectElement('#slotsPaytable'),
  slotsStatus: selectElement('#slotsStatus'),
  slotReels: selectElement('#slotReels'),
  slotsResult: selectElement('#slotsResult'),
  slotsRoomPlayers: selectElement('#slotsRoomPlayers'),
  setup: selectElement('#setup'),
  profileNameInput: selectElement<HTMLInputElement>('#profileNameInput'),
  createProfileButton: selectElement<HTMLButtonElement>('#createProfileBtn'),
  profileList: selectElement<HTMLDivElement>('#profileList'),
  startSessionButton: selectElement<HTMLButtonElement>('#startSessionBtn'),
  saveStatus: selectElement('#saveStatus'),
  switchProfileButton: selectElement<HTMLButtonElement>('#switchProfileBtn'),
  sessionLimitInput: selectElement<HTMLInputElement>('#sessionLimitInput'),
  sessionNotice: selectElement('#sessionNotice'),
  profileStats: selectElement('#profileStats'),
  auditLog: selectElement<HTMLDivElement>('#auditLog'),
  roomLobby: selectElement<HTMLDivElement>('#roomLobby'),
  roomGameTitle: selectElement('#roomGameTitle'),
  roomGameDescription: selectElement('#roomGameDescription'),
  backToLobbyButton: selectElement<HTMLButtonElement>('#backToLobbyBtn'),
  roomBrowser: selectElement<HTMLDivElement>('#roomBrowser'),
  roomNameInput: selectElement<HTMLInputElement>('#roomNameInput'),
  roomMaxPlayersInput: selectElement<HTMLInputElement>('#roomMaxPlayersInput'),
  roomRefreshButton: selectElement<HTMLButtonElement>('#roomRefreshBtn'),
  hostRoomButton: selectElement<HTMLButtonElement>('#hostRoomBtn'),
  leaveRoomButton: selectElement<HTMLButtonElement>('#leaveRoomBtn'),
  roomStatus: selectElement('#roomStatus'),
  roomMenu: selectElement<HTMLDetailsElement>('#roomMenu'),
  roomSeats: selectElement('#roomSeats'),
  tableHost: selectElement<HTMLDivElement>('#tableHost'),
  walletStack: selectElement<HTMLDivElement>('.wallet-stack'),
  moneyPill: selectElement<HTMLDivElement>('#moneyPill'),
  bankroll: selectElement('#bankroll'),
  bankrollDelta: selectElement('#bankrollDelta'),
  onTable: selectElement('#onTable'),
  houseAdvancePill: selectElement('#houseAdvancePill'),
  chipRail: selectElement<HTMLDivElement>('#chipRail'),
  chipButtons: selectElements<HTMLButtonElement>('[data-chip]'),
  moneyInput: selectElement<HTMLInputElement>('#moneyInput'),
  addMoneyButton: selectElement<HTMLButtonElement>('#addMoneyBtn'),
  subtractMoneyButton: selectElement<HTMLButtonElement>('#subtractMoneyBtn'),
  resetMoneyButton: selectElement<HTMLButtonElement>('#resetMoneyBtn'),
  shell: selectElement('#casinoShell'),
  connectionOverlay: selectElement('#connectionOverlay'),
  gameLobby: selectElement<HTMLDivElement>('#gameLobby'),
  gameLobbyTiles: selectElement<HTMLDivElement>('#gameLobbyTiles'),
  gameTabs: selectElements<HTMLButtonElement>('[data-game]'),
  playerStrip: selectElement<HTMLDivElement>('#playerStrip'),
  houseAdvancePanel: selectElement<HTMLDivElement>('#houseAdvancePanel'),
  houseAdvanceButton: selectElement<HTMLButtonElement>('#houseAdvanceBtn'),
  gameHud: selectElement<HTMLDivElement>('#gameHud'),
  hudOverflowMenu: selectElement<HTMLDetailsElement>('#hudOverflowMenu'),
  actionDock: selectElement<HTMLDivElement>('#actionDock'),
  dealButton: selectElement<HTMLButtonElement>('#dealBtn'),
  nextButton: selectElement<HTMLButtonElement>('#nextBtn'),
  hitButton: selectElement<HTMLButtonElement>('#hitBtn'),
  stickButton: selectElement<HTMLButtonElement>('#stickBtn'),
  rebetButton: selectElement<HTMLButtonElement>('#rebetBtn'),
  clearButton: selectElement<HTMLButtonElement>('#clearBtn'),
  layoutOverlayButton: selectElement<HTMLButtonElement>('#layoutOverlayBtn'),
  log: selectElement<HTMLDivElement>('#log'),
  adminTokenInput: selectElement<HTMLInputElement>('#adminTokenInput'),
  authorizeAdminButton: selectElement<HTMLButtonElement>('#authorizeAdminBtn'),
  resetAllButton: selectElement<HTMLButtonElement>('#resetAllBtn'),
  clearSavesButton: selectElement<HTMLButtonElement>('#clearSavesBtn'),
});
